version: '3'
networks:
  default:
    # Use a custom driver
    driver: bridge
services:
  postgres:
    # Если сервис основан на одном из готовых образов, используйте параметр image вместо build
    image: postgres:13
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data/
    networks:
      default:
  django-admin-panel:
    build:
      context: .
    volumes:
      - ./src/static/:/app/src/static/:ro
    networks:
      default:
    depends_on:
      # Сервис должен запуститься только после того, как postgres будет готов принимать запросы
      - postgres
    expose:
      - 8000
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/conf.d/:/etc/nginx/conf.d/:ro
#      - ./src/static/:/opt/aa/webroot/:ro
      - ./src/static/:/data/:ro
    networks:
      default:
    depends_on:
      - django-admin-panel
    ports:
      - "80:80"