version: '3'
networks:
  default:
    # Use a custom driver
    driver: bridge
services:
  postgres:
    # Если сервис основан на одном из готовых образов, используйте параметр image вместо build
    image: postgres:13
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data/
    networks:
      default:
    ports:
      # Перенаправляем запросы, поступающие к localhost:5432 на порт 5432.
      - "5432:5432"
  django-admin-panel:
    build:
      context: .
    networks:
      default:
    ports:
      # Перенаправляем запросы, поступающие к localhost:8000 на порт 8000.
      - "8000:8000"
    depends_on:
      # Сервис должен запуститься только после того, как postgres будет готов принимать запросы
      - postgres
    expose:
      - 8000
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/conf.d/:/etc/nginx/conf.d/:ro
    depends_on:
      - django-admin-panel
    ports:
      - "80:80"