version: '3'
services:
#  postgres:
#    # Если сервис основан на одном из готовых образов, используйте параметр image вместо build
#    image: postgres
#    ports:
#      # Перенаправляем запросы, поступающие к localhost:8010 на порт 8010.
#      - 5432:5432
  django-admin-panel:
    build:
      context: .
    ports:
      # Перенаправляем запросы, поступающие к localhost:8010 на порт 8010.
      - 8000:8000
#    depends_on:
#      # Сервис должен запуститься только после того, как postgres будет готов принимать запросы
#      - postgres
